apiVersion: v1
kind: Service
metadata:
  name: {{ include "exam-chart.fullname" . }}
  labels:
    {{- include "exam-chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: business
      port: 8080
      targetPort: 8080
    - name: management
      port: 8081
      targetPort: 8081
  selector:
    {{- include "exam-chart.selectorLabels" . | nindent 4 }}
