apiVersion: v1
kind: Service
metadata:
  name: {{ include "exam-chart.fullname" . }}
  labels:
    {{- include "exam-chart.labels" . | nindent 4 }}
spec:
  ports:
    - name: business
      port: {{ .Values.ports.business }}
      targetPort: {{ .Values.ports.business }}
    - name: management
      port: {{ .Values.ports.management }}
      targetPort: {{ .Values.ports.management }}
  selector:
    {{- include "exam-chart.selectorLabels" . | nindent 4 }}
